In [1]:
import numpy as np

In [2]:
#Create an array of 10 zeros

zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create an array of 10 ones
ones = np.zeros(10)+1
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#Create an array of 10 fives
ones = np.zeros(10)+5
ones

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
#### Create an array of the integers from 10 to 50
array_int = np.array(range(10,51))
array_int

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
#Create an array of all the even integers from 10 to 50
array_int_even = np.array(range(10,51,2))
array_int_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
np_matrix = np.matrix(range(0,9)).reshape(3,3)
np_matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
#Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Use NumPy to generate a random number between 0 and 1
random_np = np.random.rand(10)
random_np

array([0.06518898, 0.57314338, 0.02478222, 0.01831819, 0.12656939,
       0.95759475, 0.97285812, 0.65716048, 0.84818904, 0.17223929])

In [14]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.normal(0,1,25)

array([ 0.16670287, -0.753131  , -0.87254816, -0.6273715 , -0.06548713,
        1.1732004 , -3.39233728,  0.6002993 , -1.07005967,  0.81522857,
        0.4641189 ,  1.09452717,  1.00980773, -1.92227563, -1.10495638,
        0.95236259,  0.98588856,  0.47040004,  0.7373706 ,  0.40704894,
        0.58528819,  0.05403521, -1.03127912, -1.21461784, -1.03648861])

In [16]:
#Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [51]:
# HERE IS THE GIVEN MATRIX CALLED MAT
# USE IT FOR THE FOLLOWING TASKS
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3,4]

20

In [60]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [61]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[-1:]

array([[21, 22, 23, 24, 25]])

In [62]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
#Get the sum of all the values in mat
mat.sum()

325

In [66]:
#Get the sum of all the values in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [108]:
#Bonus Question
# We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])