# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.random.randint(0,100,10)

In [3]:
#Show
arr

array([53, 16, 11,  4, 66, 28, 71, 11, 25, 77])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Get a value at an index
arr[4]

66

In [5]:
#Get values in a range
arr[1:5]

array([16, 11,  4, 66])

In [6]:
#Get values in a range
arr[0:5]

array([53, 16, 11,  4, 66])

In [7]:
arr[:5]

array([53, 16, 11,  4, 66])

In [8]:
arr[3:]

array([ 4, 66, 28, 71, 11, 25, 77])

In [12]:
arr[len(arr) - 5]

28

In [13]:
arr[-5]

28

In [14]:
arr[-4:]

array([71, 11, 25, 77])

In [16]:
arr

array([53, 16, 11,  4, 66, 28, 71, 11, 25, 77])

In [15]:
arr[0:7:2]

array([53, 11, 66, 71])

In [18]:
arr[0::3]

array([53,  4, 71, 77])

In [24]:
arr[6::-1]

array([71, 28, 66,  4, 11, 16, 53])

In [25]:
arr[6:0:-1]

array([71, 28, 66,  4, 11, 16])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [26]:
#Setting a value with index range (Broadcasting)
arr[:5]=100

#Show
arr

array([100, 100, 100, 100, 100,  28,  71,  11,  25,  77])

In [31]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.random.randint(0,50,10)

#Show
arr

array([ 3, 11,  9, 12, 24,  6, 18, 35, 24, 11])

In [32]:
#Important notes on Slices
slice_of_arr = arr[0::3]

#Show slice
slice_of_arr

array([ 3, 12, 18, 11])

In [33]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99])

Now note the changes also occur in our original array!

In [34]:
arr

array([99, 11,  9, 99, 24,  6, 99, 35, 24, 99])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [12]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [35]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [36]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [37]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][1]

25

In [39]:
# Getting individual element value
arr_2d[1,1]

25

In [40]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [41]:
arr_2d[0::2,0::2]

array([[ 5, 15],
       [35, 45]])

In [42]:
arr_2d[-2:,0::2]

array([[20, 30],
       [35, 45]])

In [43]:
#Shape bottom row
arr_2d[-1]

array([35, 40, 45])

## Conditional Selection

This is a very fundamental concept that will directly translate to pandas later on, make sure you understand this part!

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [44]:
arr = np.random.randint(0,100,50)
arr

array([74,  4, 75, 74, 54, 78, 34, 84, 82,  7, 99, 82, 86, 86, 42, 75,  7,
       80, 84, 77, 27,  3, 39, 97, 79, 90, 87, 43, 81, 12, 37, 56, 76, 19,
       78, 49, 18, 68, 41,  2, 68, 27, 90,  5, 34, 97, 30, 79, 68, 54])

In [45]:
arr > 20

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True])

In [58]:
bool_arr = ((arr % 2) == 1)

In [59]:
bool_arr

array([False, False,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False, False,  True, False,  True,
       False, False,  True, False, False,  True, False,  True, False,
        True, False,  True, False, False])

In [60]:
arr

array([74,  4, 75, 74, 54, 78, 34, 84, 82,  7, 99, 82, 86, 86, 42, 75,  7,
       80, 84, 77, 27,  3, 39, 97, 79, 90, 87, 43, 81, 12, 37, 56, 76, 19,
       78, 49, 18, 68, 41,  2, 68, 27, 90,  5, 34, 97, 30, 79, 68, 54])

In [61]:
arr[bool_arr]

array([75,  7, 99, 75,  7, 77, 27,  3, 39, 97, 79, 87, 43, 81, 37, 19, 49,
       41, 27,  5, 97, 79])

In [66]:
arr = np.random.randint(1,100,80)

In [68]:
arr = arr.reshape(16,5)
arr

array([[57,  5, 22, 73, 20],
       [75, 38, 65, 89, 97],
       [65, 72, 52, 55, 13],
       [47, 84, 85, 81, 32],
       [ 9, 97, 21, 32, 72],
       [70, 71,  9, 83, 60],
       [97, 68, 78, 70, 30],
       [99, 51, 58, 71, 41],
       [ 8, 96, 65, 57, 99],
       [29, 44, 65, 33, 56],
       [95, 68, 48, 35, 39],
       [21, 56, 76, 13, 39],
       [98, 59, 19, 75, 32],
       [20, 92, 41, 93, 26],
       [33, 27, 51, 40, 77],
       [11, 92, 62, 78, 95]])

In [64]:
arr[arr<15]

array([ 1, 10,  5,  4,  5, 11])

In [65]:
# Select Odd numbers
arr[arr%2 == 1]

array([53, 77, 89, 89,  1, 95, 61, 71, 55, 89, 31, 81, 21, 99, 89,  5, 29,
       43, 89, 85, 87, 97, 31, 51, 93, 69, 49, 83, 89, 87, 51, 19, 33, 91,
       21, 59, 71, 27,  5, 95, 11, 27, 27, 97])